services:
  mysql:
    image: mysql:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - ./container_data:/var/lib/mysql
    command:
      - --port=3307
      - --bind-address=127.0.0.1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-P", "3307"]
      interval: 10s
      timeout: 5s
      retries: 3

  tg_bot:
    build: .
    restart: always
    network_mode: host
    volumes:
      - .:/usr/src/app
      - /var/lib/marzban/db.sqlite3:/usr/src/app/db/marzban_db.sqlite3
    depends_on: 
      mysql:
        condition: service_healthy
    env_file:
      - .env
